### ISSUE TITLE
Can't release payment to merchant

### ISSUE THREAD

**Issue by TAiS46** [OpenBazaar/OpenBazaar#1202]
If I try to release the payment to the merchant, the log is showing following error:
ProtocolHandler - ERROR - Invalid argument

**Comment by hoffmabc** [comment]
Which branch or version are you using?

**Comment by TAiS46** [comment]
develop branch

**Comment by TAiS46** [comment]
no way to get my bitcoins out?

**Comment by hoffmabc** [comment]
Right now the develop branch uses eligius pool to release transactions and they have since disabled that method. Our 0.4 release is switching to a different method and will work again. You have the keys among you the merchant and notary to craft a multisig tx manually, but I do not have a manual or instructions on how to do so available. Please do not use any bitcoins that you don't mind losing while testing this software. It has bugs and is not ready for release obviously.

**Comment by hoffmabc** [comment]
@TAiS46 I'm going to close this for now since it's an old version. Please submit a new ticket if this is still occurring on 0.4.
