### ISSUE TITLE
Questions about notary feasibility

### ISSUE THREAD

**Issue by taoeffect** [OpenBazaar/OpenBazaar#1314]
Copied from [here](https://github.com/OpenBazaar/OpenBazaar/issues/1309#issuecomment-105400679):

> - Notaries are a third-party that can be gamed by the merchants themselves to screw customers and competitors over.

Thinking this over, it's worth asking how likely that possibility will be.

X = benefit to merchant of being their own notary
Y = Cost of getting caught
Z = Probability of getting caught
A = reward to random person for being a notary

Note that `X = A + e` (where `e` is additional benefit a merchant gets by being a notary that normal people don't get).

In other words Merchants are far more incentivized than anyone else to be a notary.

Theorem 1:

```
If:
    
    X - Z*Y > A

Then:

   Most notaries will be malicious merchants
```

Theorem 2:

```
Increasing A does not improve this situation at all, only increasing Z and/or Y does.
```

So if you can't guarantee that Z and Y will be high, you are designing a system that is predisposed to screwing a bunch of people over.

One way to improve the situation is to somehow make it more likely that a "fair" notary will be used in a transaction. But how would you go about doing that? That seems like another can of worms. If that can't be reliably done, I only see BitMarkets-style 2-of-2 multisig as a solution (and in general it seems to me like a good default to use).

**Comment by drwasho** [comment]
MAD multisig offers zero redundancy and asks merchants to risk far more than they need to purchase an item.

```
Alice is selling shoes for 0.1 BTC that Bob wants to buy. They create a multsig address, Bob deposits 0.1 BTC and Alice deposits X% of 0.1 BTC as a security deposit (some variations have Bob also risking additional capital). 
```

If one person loses their key, game over. If one person is incapacitated, game over. If there is a dispute that cannot be resolved by either party, game over. If one party decides to screw you for the lulz, game over.

This utterly fails on the consumer level. I can imagine telling my relatives that fire up OpenBazaar for the first time that in order to buy those shoes for 0.1 BTC, they need to throw in an extra 0.025 BTC as a security deposit... and that if something goes wrong with the merchant, all their money is gone forever. Or if I tell them in order to sell their shoes for 0.1 BTC they may have to risk up to another 0.1 BTC on a potential buyer... and if anything goes wrong with them, their money is gone forever (and their shoes if problems occur after shipping).

---

A compromised notary is a big risk, but a manageable one... certainly more manageable than MAD multisig. 

It is true that if you have a compromised notary, it is game over and your money is also gone forever. 

This is why trust requirements from a notary can be more stringent than individual requirements from the buyer and seller. A notary can expose their _meatspace_ identity and details for legal recourse (i.e. legal accessibility) in addition to other measures that I have written about here: https://gist.github.com/drwasho/a0225f5455e508095ac2

BitRated is an excellent example of a group that is doing this very thing right now. They're actually an example of a _chama_ in action, or a private web-of-trust association that can know each other's _meatspace_ identity and hold security deposits between members.

With notaries involved, when you're conducting trade, you have an open market to pick from and assess the risk. A notary that no one has ever heard of with few details is unlikely to be selected compared to BitRated on the network, which has the contact details and organisational leverage for their network of notaries.

--- 

Bottom-line, and I wrote this in #1309, OpenBazaar **is not forcing one model of payment** on the network. We will support:

1. Direct payment (Alice -> Bob; no multisig) - ideal when a deep level of trust has been established between buyer and seller. 
2. MAD escrow (Alice + Bob, 2-of-2 multisig) - for more private and less risk transactions
3. Notary escrow (Alice + Bob + Notary, 2-of-3 multisig; market for notaries) -  for less private, more risky transactions
4. Notary pool escrow (Alice + Bob + Notary(n) multisig) - for less private, high risk transactions

The descriptions I added above where my own guess of their use.

**Finally:** a deep value within the dev core of OpenBazaar is 'why not both'. My own doubts about MAD multisig shouldn't prevent anyone from engaging in those types of transactions (and visa versa).

**Comment by taoeffect** [comment]
Thanks so much for that detailed overview of the situation.

Is notary selection a customer decision or a merchant decision or both? (How does it work?)

Adding @stevedekorte

**Comment by taoeffect** [comment]
> If one person loses their key, game over. If one person is incapacitated, game over. If there is a dispute that cannot be resolved by either party, game over. If one party decides to screw you for the lulz, game over.

"game over" here shouldn't be all that bad (so you lost ~$100, oh well). The "game over" in a malicious notary situation might be worse?

And it's not so much the "game over" aspect either, it's also about the ROI on the development and maintenance effort with notaries.

However, the idea of treating notaries are simply other merchants would go a long way to addressing the both the cost of development and the "elegantness" of the entire situation, and [you seem to agree](https://github.com/OpenBazaar/OpenBazaar/issues/1309#issuecomment-105415735), so if that's the case I'm on board. :)

> This utterly fails on the consumer level...

Those are some valid points as well. I'll let responding to that to @stevedekorte (if he wants to).

I think the concerns in the OP would be addressed if:

1. MAD multisig is a readily available option (seems like it might be)
2. Notaries are treated like merchants and can be rated just like merchants.

(2) goes a long way to answering [the question of](https://gist.github.com/drwasho/a0225f5455e508095ac2#3-accredited-notaries):

> how users will choose notaries within *OpenBazaar*?

**Comment by stevedekorte** [comment]
FWIW, I recommend giving some thought to the last four words of Satoshi's first public sentence: "“I've been working on a new electronic cash system that's fully peer-to-peer, with no trusted third party.”

**Comment by drwasho** [comment]
> "“I've been working on a new electronic cash system that's fully peer-to-peer, with no trusted third party.”

Heard of miners? They're essentially notaries selected by SHA256 lottery.

**Comment by taoeffect** [comment]
> Heard of miners? They're essentially notaries selected by SHA256 lottery.

That's a very neat way to think of it.

**Comment by drwasho** [comment]
Sorry I don't mean to be snide in my comment.

My point is that even in Bitcoin we don't have perfect trustless solutions... we have solutions that are damn good with fewer trade-offs. Creating a market for notaries, in my view, will achieve a similar goal that is consumer friendly.

**Comment by stevedekorte** [comment]
drwasho, Satoshi's insight wasn't that crypto signing could be used to verify transfers (prior systems did this), it's that proof of work could order them in a trustless way (given some economic game theory on the distribution of hash power).

**Comment by stevedekorte** [comment]
Likewise, economic game theory applied to multisig mutual deposits suggests how we can build trustless markets. 

All major human advancement has effectively come from the removal of trusted third parties. Science was the first means to avoid trusted third parties. It didn't replace one church with another or many. It provided a means for anyone to verify/deny physical claims about the world. Bitcoin gave us the same power for digital ledgers and two party escrow allows us to extend this to physical ledgers (physical movement based transfers of ownership).

**Comment by taoeffect** [comment]
The biggest problem that can happen with notaries is if a monopoly (or a cartel) is allowed to form out of them.

That can happen if merchants decide to only accept customers who agree to use "one of the Big Five" or w/e.

It is not at all uncommon for that to happen in a market, and that is why two-party escrow remains important.

**Comment by rippler** [comment]
> That can happen if merchants decide to only accept customers who agree to use "one of the Big Five" or w/e

That assumes that they benefit more from being a notary than competing on the free market. Who, except under threat of force (i.e. government services), would accept to deal with such merchants and why?

**Comment by stevedekorte** [comment]
I'm getting the impression that the assumption behind anonymous escrow is that it named escrow survives sybil attacks and long cons so it should too. But this misses that the cost equation changes when there is no door to knock on when escrow fraud is committed. For anonymous escrow, cons aren't just a profitable activity, they are *the most profitable activity* as the cost of running a script to execute them is effectively zero.

**Comment by rippler** [comment]
> This approach is a form of self-regulation, whereby accreditation is earned after demonstrating compliance. The accrediting organisation can also hold the surety bond in the event that an accredited notary defrauds a client. In this scenario, a corrupt notary is excluded from the organisation, their **surety bond is forfeit** (perhaps used to compensate a defrauded member), and they lose their public accreditation with the association. A notary may choose to become accredited from several such organisations to bootstrap trust.

https://github.com/OpenBazaar/OpenBazaar/blob/master/docs/05%20Notary%20Selection%20in%20OpenBazaar.md

Notaries, like everyone else, are can also burn a certain amount of BTC as a sign of commitment to the address from which they conduct business.  
So the cost is not really zero. If a notary simultaneously defrauds 10 people to the tune of 0.3 BTC each, it may not work out for him if he burned 5 or 10 BTC. Based on various factors and personal risk tolerance people would look for exposure that is a fraction of the value of the surety bond + burned amount.

**Comment by stevedekorte** [comment]
A burn provides an easily automated way to construct the trust to be exploited. If a good faith escrow agent can still profit after a burn of X, then a bad faith one can profit even more so.

**Comment by rippler** [comment]
In the quoted text it says clearly the accrediting organisation of which the notary is a member would determine (in case of a surety bond). 
If I am buying or selling a cheap domain name (say, $9.90), I'd rather pick a notary from a competing registrar or maybe a Web designer that I heard of before, than spend $2 worth of my time exploring (or using) other options. 
It's not meant to be foolproof. it's just one of options and it's certainly feasible.

**Comment by hoffmabc** [comment]
I have a quick question and I'm not trolling here. Let's say you're selling a car that is valued at something like $40,000 USD. I'm expected to put up some amount (in your example ~25%) so let's say $10,000. The buyer is expected to put up twice that so $20,000. So now to sell a car, which happens on eBay Motors all the time there is now $30,000 USD in at risk account. This whole idea seems absolutely ludicrous at larger amounts. I mean yeah who the fuck cares for a t-shirt or something because it's negligible, but also depending on the profit margin and amount risked it might still be worth something. I also realize you could adjust the % of sale that is at risk, but it would still need to be significant enough to discourage fraud. Can someone please explain how this could ever be considered as a reasonable request of users outside of companies or businesses that have huge cash reserves (in Bitcoin as well mind you) that would be willing to do this? Am I missing something here?

**Comment by stevedekorte** [comment]
hoffmabc, that's a good point but the payment amount itself is sufficient to be a problem even without considering the size of the deposit. Two party escrow only works if both sides are willing to punitively give up their input amount to punish fraud on the other side, which they may not do if the amount is above several months salary. But of the hundreds of thousands of economic transactions people make in their lifetimes, how many involve a shippable item that exceeds several months salary and isn't from a already trusted party? A used vehicle purchase is the only example that comes to mind. For this case (and for certain types of services), I agree it's an issue that some form of trust may be needed to solve but it will still need to involve the agent being an intermediary in the delivery in order to inspect the item if it is to be able to fairly resolve disputes.

**Comment by hoffmabc** [comment]
@stevedekorte so why couldn't a notary for instance offer some sort of shipping verification and service that allows this to be implemented? Shipping is an issue, but perhaps that industry is ripe for disruption as well? This sounds more like an out of scope gap to be filled than a hit to the notary model. I have a feeling that notaries may just end up splitting the amount between each party in a lot of cases that can't be proven one way or another, but this is still better than unfairly penalizing either side. I could see the MAD model leading to this conclusion as well. 

In respect to the amount of a sale having to be dramatically high to be an issue this is relative. For some people a $300 laptop is all their expendable income and coming up with extra money for a deposit just won't be feasible. For others it's nothing and for scammers probably worth losing altogether. It's hard to make a blanket statement on how to handle something that means so much to one person and hardly anything to another. This creates unbalanced incentives.

I think we're also ignoring the benefits of additional services that notaries may provide to users.

**Comment by stevedekorte** [comment]
@hoffmabc "Why couldn't a notary for instance offer some sort of shipping verification..." There are relatively standard skills to assess the quality of a used car, but how does this work for the vast array of items on a site like eBay and is it affordable for small items? Expertise aside, the cost of human labor to open, inspect, repack an reship an item would may exceed the cost of many items. It also removes the privacy of the transaction and extends any legal liability involved to the agent themselves.

**Comment by stevedekorte** [comment]
Another quote worth considering: "Game theory is very weak as a security model, but on internet probably superior to reputation, and certainly to assuming trusted third parties." - Nick Szabo

**Comment by drwasho** [comment]
Notaries aren't going anywhere and it's an option alongside other ways of paying with Bitcoin... people will decide what they'll prefer.

So let it be written, so let it be done.
