### ISSUE TITLE
Purchase Contract - Price 

### ISSUE THREAD

**Issue by bglassy** [OpenBazaar/OpenBazaar#1352]
When viewing a contract to purchase, the price of the contract should be displayed in it's current USD and EUR value as-well. Not just BTC.

**Comment by rippler** [comment]
* There's existing feature request to pull this info from external sources
* If contract price is displayed in fiat, how can be goods quoted in BTC? If buyer due to a rise in BTC exchange rate pays less than the agreed BTC price, then he didn't do his part.
* Which fiat should be used? 

I don't care if there's an option to (also) use fiat, but I am against making fiat the default. That defeats the purpose of BTC.

**Comment by bglassy** [comment]
Didn't see the existing feature request. Closed.
