### ISSUE TITLE
Peer information storage in multiple places and what are the differences?

### ISSUE THREAD

**Issue by dong77** [OpenBazaar/OpenBazaar#903]
Guys, I'm trying to read some of the code inside the /node directory. It seems to me some peer information are saved in 1) dht's **activePeers** list, 2) dht's **routingTable** or 3) dht's **knownNodes** and 4) the **DB**. My question is : why we need to maintain the first 3 variables and what are the differences between the information saved in these 4 places? Another user [benemorius] also wants to know the answers.
Thank you.

**Comment by hoffmabc** [comment]
This has changed a lot (but not enough) since you commented here. I think our first approach has been to manage state of connections separately from the DHT. DHT libraries usually handle the networking and in our case we had separate ZeroMQ sockets. This was a poor attempt at segregating these but yet keeping them in sync. We plan to move to more modularized design of the DHT and networking code and will be improving this over the next couple of months.

**Comment by hoffmabc** [comment]
Closing for now.
