### ISSUE TITLE
pysqlcipher amalgamation vulnerability

### ISSUE THREAD

**Issue by dionyziz** [OpenBazaar/OpenBazaar#964]
pysqlcipher's amalgamation vulnerability makes our users vulnerable to attackers with simple network access, which is well within our threat model:

https://github.com/leapcode/pysqlcipher/issues/13

This is a critical security issue which we must resolve. This issue is here to keep track of pysqlcipher's progress on resolving it; as issues with the project have been taking time to resolve, a temporary fork may become necessary. Let's keep track of it here.

**Comment by Renelvon** [comment]
We have upgraded dependencies to use the latest version of `pysqlcipher`, which downloads the amalgamation from a [secure URL](https://github.com/leapcode/pysqlcipher/blob/develop/setup.py#L119). Maybe we should close this issue?

**Comment by yurivict** [comment]
Download was insecure not because it was 'http' and not 'https', download was insecure because it didn't check the file hash, therefore being vulnerable to MITM attack.

Now py-sqlcipher allows to use libsqlcipher as a dependency instead of amalgamation download, see README https://github.com/leapcode/pysqlcipher/blob/develop/README.rst

This is what should be used by OpenBazaar. Please make sure OpenBazaar uses py-sqlcipher without it downloading amalgamation.

**Comment by hoffmabc** [comment]
Closing this @Renelvon @yurivict @dionyziz since we are no longer using pysqlcipher for this project at this time.
